# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
#url: http://github.com/lihuimintu/lihuimintu.github.io
date_format: "ordinal"
title: ubuntu咸鱼
subtitle: "Simple maybe, but not easy"
description: "Simple maybe, but not easy"
keywords: Algorithm,Dada Struct, Linux,Java
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zemingyan
#organization: UESTC
#organization_url: http://organization_url.githbu.io
github_username: zemingyan
location: KunMing
email: buxiaode233@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home


  -
    href: /categories/
    label: Blog
   


  -
    href: /open-source/
    label: Open-source
   

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Link

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: git@github.com:zemingyan/zemingyan.github.io.git

# ---------------- # 
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
#comments_provider: gitalk
comments_provider: gitalk


# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wenjun d

    
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zemingyan
    repo: zemingyan.github.io
    oauth:
        client_id: e171e4ef3d8128b9ad4c
        client_secret: 8965fddcd7cfe0ba4bfb49550e23850dea558db3
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zemingyan
    repo: zemingyan.github.io
    clientID: e171e4ef3d8128b9ad4c
    clientSecret: 8965fddcd7cfe0ba4bfb49550e23850dea558db3
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-148378051-1

# ---------------- #
#    Counter     #
# ---------------- #
# 使用的是learncloud，appid和key更换成自己的
# 先关闭
leancloud:
  enable: false
  app_id: EfLTUbK2fJ0dYLAq609NQ2k4-gzGzoHsz
  app_key: 5Agxeshbunhh9y6XQftwEvGj
